export const PHONE_SUBMIT = 'PHONE_SUBMIT'
export const PHONE_SUBMIT_SUCCESS = 'PHONE_SUBMIT_SUCCESS'
export const PHONE_SUBMIT_FAILURE = 'PHONE_SUBMIT_FAILURE'

export const OTP_SUBMIT = 'OTP_SUBMIT'
export const OTP_SUBMIT_SUCCESS = 'OTP_SUBMIT_SUCCESS'
export const OTP_SUBMIT_FAILURE = 'OTP_SUBMIT_FAILURE'